version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    expose:
      - 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
      - MAPPING_URL=mapping.json
      - INDEX_NAME=id
      - ES_URL=http://es:9200
    depends_on:
      - db
      - es
    networks:
      - es-net
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    networks:
      - es-net
    environment:
      - POSTGRES_USER=fastapi_traefik
      - POSTGRES_PASSWORD=fastapi_traefik
      - POSTGRES_DB=fastapi_traefik
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"

    networks:
      - es-net
    expose:
      - 9200
    ports:
      - "9200:9200"
networks:
  es-net:
    driver: bridge
volumes:
  postgres_data: